server:
  port: 9002
spring:
  application:
    name: zuul-sentinel
zuul:
  routes:
    rest-server:
      path: /hello2/**
      strip-prefix: false
      url: http://localhost:9000

project:
  name: ${spring.application.name}
csp:
  sentinel:
    app:
      type: 1
    dashboard:
      server: localhost:8080
    api:
      port: 8720